# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vp_setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(301, 315)
        MainWindow.setMinimumSize(QtCore.QSize(301, 315))
        MainWindow.setMaximumSize(QtCore.QSize(301, 315))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(301, 315))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"                background-color: #2b2b2b;\n"
"                color: #f0f0f0;\n"
"                font-size: 12px;\n"
"            }\n"
"            QLineEdit {\n"
"                background-color: #3c3f41;\n"
"                color: #f0f0f0;\n"
"                border: 1px solid #555555;\n"
"                padding: 4px;\n"
"            }\n"
"            QPushButton {\n"
"                background-color: #3c3f41;\n"
"                color: #f0f0f0;\n"
"                border: 1px solid #555555;\n"
"                padding: 4px;\n"
"                border-radius: 4px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #454545;\n"
"            }")
        MainWindow.setIconSize(QtCore.QSize(256, 256))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LBL_BASE = QtWidgets.QLabel(self.centralwidget)
        self.LBL_BASE.setGeometry(QtCore.QRect(10, 20, 104, 14))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.LBL_BASE.setFont(font)
        self.LBL_BASE.setObjectName("LBL_BASE")
        self.LBL_VPNAME = QtWidgets.QLabel(self.centralwidget)
        self.LBL_VPNAME.setGeometry(QtCore.QRect(10, 90, 107, 14))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.LBL_VPNAME.setFont(font)
        self.LBL_VPNAME.setToolTip("")
        self.LBL_VPNAME.setObjectName("LBL_VPNAME")
        self.LBL_VPVAR = QtWidgets.QLabel(self.centralwidget)
        self.LBL_VPVAR.setGeometry(QtCore.QRect(10, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.LBL_VPVAR.setFont(font)
        self.LBL_VPVAR.setObjectName("LBL_VPVAR")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(106, 229, 91, 24))
        self.okButton.setCheckable(False)
        self.okButton.setDefault(True)
        self.okButton.setFlat(False)
        self.okButton.setObjectName("okButton")
        self.vehicleNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.vehicleNameInput.setGeometry(QtCore.QRect(10, 40, 281, 31))
        self.vehicleNameInput.setObjectName("vehicleNameInput")
        self.descriptionInput = QtWidgets.QLineEdit(self.centralwidget)
        self.descriptionInput.setGeometry(QtCore.QRect(10, 110, 281, 31))
        self.descriptionInput.setToolTip("")
        self.descriptionInput.setWhatsThis("")
        self.descriptionInput.setClearButtonEnabled(False)
        self.descriptionInput.setObjectName("descriptionInput")
        self.variationsInput = QtWidgets.QLineEdit(self.centralwidget)
        self.variationsInput.setGeometry(QtCore.QRect(10, 180, 281, 31))
        self.variationsInput.setObjectName("variationsInput")
        self.LBL_URL = QtWidgets.QLabel(self.centralwidget)
        self.LBL_URL.setGeometry(QtCore.QRect(10, 270, 141, 16))
        self.LBL_URL.setTextFormat(QtCore.Qt.AutoText)
        self.LBL_URL.setWordWrap(False)
        self.LBL_URL.setOpenExternalLinks(True)
        self.LBL_URL.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.LBL_URL.setObjectName("LBL_URL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 47, 13))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Structure Generator"))
        self.LBL_BASE.setText(_translate("MainWindow", "Base vehicle name:"))
        self.LBL_VPNAME.setText(_translate("MainWindow", "Vehicle Description:"))
        self.LBL_VPVAR.setText(_translate("MainWindow", "Variations:"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.vehicleNameInput.setStatusTip(_translate("MainWindow", "Define internal name of the vehicle"))
        self.vehicleNameInput.setPlaceholderText(_translate("MainWindow", "vpbullet"))
        self.descriptionInput.setStatusTip(_translate("MainWindow", "As name appears in Vehicle Select"))
        self.descriptionInput.setPlaceholderText(_translate("MainWindow", "Ford Mustang Fastback"))
        self.variationsInput.setStatusTip(_translate("MainWindow", "Paint/colour selections (seperated by vertical bar \"|\")"))
        self.variationsInput.setPlaceholderText(_translate("MainWindow", "Green|Blue|Red|White|Classic Chrome"))
        self.LBL_URL.setStatusTip(_translate("MainWindow", "Visit author\'s website"))
        self.LBL_URL.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://chasseyblue.com\"><span style=\" text-decoration: underline; color:#ffffff;\">https://chasseyblue.com</span></a></p></body></html>"))
        self.label.setText(_translate("MainWindow", "v1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
